config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/styles', to: 'pages#styles'
  get '/contact', to: 'messages#new', as: 'new_message'
  post '/contact', to: 'messages#create', as: 'create_message'
  resources :orders, only: [:show, :create, :edit, :update] do
    resources :payments, only: [:new, :create]
  end
  get '/orders/:order_id/confirmation', to: 'orders#confirmation', as: 'confirmation'
  get 'orders/:order_id/thanks', to: 'orders#thanks', as: 'thanks'
  get '/mentions-legales', to: "pages#mentions_legales", as: 'mentions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mail.rb
class Mail < ApplicationRecord
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body

  validates :name, :email, :body, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :shipping
  # belongs_to :product

  monetize :amount_cents

  validates :user_email, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :product_images

  monetize :price_cents
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :orders

  monetize :price_cents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message received, thanks!"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    calendar = Product.find(params[:calendar_id])
    order = Order.new(
      product_name: calendar.name,
      amount: calendar.price,
      state: "pending",
      user_email: params[:user_email]
    )
    order.shipping = Shipping.first
    if order.save
      redirect_to edit_order_path(order)
    elsif order.errors.messages[:user_email].first == "can't be blank"
      flash[:alert] = "email #{order.errors.messages[:user_email].first}"
      redirect_to root_path
    else
      flash[:alert] = "something went wrong"
      redirect_to root_path
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(set_order_params)
    @order.shipping = Shipping.find_by(name: params[:order][:shipping])
    if @order.save
      redirect_to confirmation_path(@order)
    else
      render :edit
    end
  end

  def shipping
    @shippings = Shipping.all
    @order = Order.find(params[:order_id])
  end

  def confirmation
    @order = Order.find(params[:order_id])
    @total_amount = @order.amount + @order.shipping.price
  end

  def thanks
    @order = Order.find(params[:order_id])
    # raise
  end

  private

  def set_order_params
    params.require(:order).permit(:first_name, :last_name, :address, :zipcode, :city, :country)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @calendar = Product.find_by(name: 'maxi calendrier')
    @order = Order.new
  end

  def styles
  end

  def mentions_legales

  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
  customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @order.amount_cents,
    description:  "Payment for #{@order.product_name} for order #{@order.id}",
    currency:     @order.amount.currency
  )

  @order.update(payment: charge.to_json, state: 'paid')
  OrderMailer.thank_you(@order).deliver_now
  redirect_to thanks_path(@order)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

private

  def set_order
    @order = Order.find(params[:order_id])
    # raise
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helpers.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>deux mille dix neuf</title>
    <meta name="description" content="maxi calendrier un peu géant à accrocher chez soi pour ne rater absolument aucun évenement.">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="deux mille dix neuf - maxi calendrier pour l'année 2019." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="deuxmilledixneuf-fb-cover.jpg" />
    <meta property="og:description" content="maxi calendrier un peu géant à accrocher chez soi pour ne rater absolument aucun évenement." />
    <meta property="og:site_name" content="deux mille dix neuf - maxi calendrier pour l'année 2019." />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@camvillard">
    <meta name="twitter:title" content="deux mille dix neuf - maxi calendrier pour l'année 2019.">
    <meta name="twitter:description" content="maxi calendrier un peu géant à accrocher chez soi pour ne rater absolument aucun évenement.">
    <meta name="twitter:creator" content="@camvillard">
    <meta name="twitter:image:src" content="deuxmilledixneuf-fb-cover.jpg">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>

  <body id="<%= controller_name %>-<%= action_name %>">
    <%= render "partials/shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "partials/shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://cdn.jsdelivr.net/npm/sharer.js@latest/sharer.min.js"></script>

  </body>
</html>

app/views/messages/ new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.email_field :email, placeholder: 'email' %>
  <%= f.text_area :body, placeholder: 'body' %>
  <%= f.submit 'Send' %>
<% end %>

app/views/messages/new.html.erb
<h1>hello from new</h1>


<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.text_field :email, placeholder: 'email' %>
  <%= f.text_field :body, placeholder: 'body' %>
  <%= f.submit 'envoyer' %>
<% end %>

app/views/orders/confirmation.html.erb
<div class="details-content">

  <div class="content-text">

    <div class="header">
      <h1>confirmation de la commande</h1>
      <h5><%= @order.product_name %></h5>

      <p class="disclaimer">attention : si vous avez choisi l'option de ramassage chez Bouche Bée, notez que la boutique est fermée jusqu'au 14 janvier.</p>
    </div>

    <div class="content-details">

      <h6>livré à :</h6>
      <p>
        <%= @order.first_name + ' ' + @order.last_name %> <br>
        <%= @order.address %> <br>
        <%= @order.zipcode %> <br>
        <%= @order.city %> <br>
      </p>

    </div> <!-- end of details -->

    <div class="content-details">
      <h6>livraison :</h6>
      <p>
        <%= @order.shipping.name %>
        <%= humanized_money_with_symbol(@order.shipping.price) %>
      </p>
    </div>

    <div class="content-details">
      <h5>montant total : <span class="total-amount"><%= humanized_money_with_symbol(@order.amount + @order.shipping.price) %></span> </h5>
    </div>

    <!-- stripe form for payment -->
    <div class="content-details">
      <%= form_tag order_payments_path(@order) do %>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="calendar"
          data-email="<%= @order.user_email %>"
          data-description="<%= @order.product_name%>"
          data-amount="<%= @order.amount_cents + @order.shipping.price_cents %>"
          data-label="payer la commande"
          data-currency="<%= @order.amount.currency %>">
        </script>
      <% end %>
    </div>

  </div> <!-- end of content-text -->

  <div class="content-image">
    <%= image_tag 'deuxmilledixneuf-portrait-1.jpg' %>
  </div> <!-- end of content-image -->

</div> <!-- end of details-content -->

app/views/orders/edit.html.erb
<div class="details-content">

  <div class="content-text">

    <div class="header">
      <h1>informations de livraison</h1>
      <h5><%= @order.product_name %></p>
    </div> <!-- end of header -->

    <div class="content-details">
      <%= simple_form_for @order do |f| %>
        <%= f.input :first_name, placeholder: 'prénom', label: false %>
        <%= f.input :last_name, placeholder: 'nom de famille', label: false %>
        <%= f.input :address, placeholder: 'addresse', label: false %>
        <%= f.input :zipcode, placeholder: 'code postal', label: false %>
        <%= f.input :city, class: 'small-input', placeholder: 'ville', label: false %>
        <%= f.collection_radio_buttons :shipping, Shipping.all, :name, :description %>
        <button class="button">commander</button>

        <%#= f.button :submit, class: 'button', value: 'confirmer la commande' %>
      <% end %>

    </div> <!-- end of content details -->

  </div> <!-- end of content-text -->

  <div class="content-image">
    <%= image_tag 'deuxmilledixneuf-portrait-1.jpg' %>
  </div> <!-- end of content-image -->

</div> <!-- end of details-content -->

app/views/orders/shipping.html.erb
<h1>informations de livraison</h1>

<p><%= @order.product_name %></p>


<%= simple_form_for @order do |f| %>
  <%= f.input :first_name, placeholder: 'prénom', label: false %>
  <%= f.input :last_name, placeholder: 'nom de famille', label: false %>
  <%= f.input :address, placeholder: 'addresse', label: false %>
  <%= f.input :zipcode, placeholder: 'code postal', label: false %>
  <%= f.input :zipcode, placeholder: 'ville', label: false %>
  <%= f.input :zipcode, placeholder: 'pays', label: false %>
  <%= f.collection_radio_buttons :shipping, Shipping.all, :name, :description %>
  <%= f.button :submit %>
<% end %>

app/views/orders/show.html.erb
<h1>order n° <%= @order.id %> </h1>

<ul>
  <li>Status: <%= @order.state %></li>
  <li>Item: <%= @order.product_name %></li>
  <li>Amount: <%= humanized_money_with_symbol(@order.amount) %></li>
<ul>

app/views/orders/thanks.html.erb
<div id="thanks-content">

  <div id="thanks-header">
    <h1>merci pour votre commande !</h1>
    <h5>les calendriers seront expédiés à partir du 27 décembre.</h5>
  </div>

  <div id="thanks-text">
    <p>bien sûr, puisque nous sommes au 21ème siècle, un courriel vous sera envoyé à ce moment là. d'ici là - toujours puisque nous sommes au 21ème, voici toute une multitude de trucs que vous pouvez faire en attendant.</p>
    <ul>
      <li><%= link_to 'télécharger la version mini à imprimer', ENV['LINK_TO_CALENDAR'], class: "big" %></li>
      <li><%= link_to "offrir un calendrier à un ami", root_path %></li>
      <li><a data-sharer="twitter"
             data-title="maxi calendrier deux mille dix neuf"
             data-url="<%= root_url %>"
             data-module-net="hashtag">partager sur twitter</a></li>
      <li><a data-sharer="facebook"
             data-module-net="hashtag"
             data-url="<%= root_url %>">partager sur facebook</a></li>

    </ul>

  </div>

  <div id="thanks-footer">
    <%= link_to root_path do %>
      <h2 class="button-inverted">deux mille dix neuf</h2>
    <% end %>
  </div> <!-- #thanks-footer -->

</div>

app/views/pages/contact.html.erb
<h1>hello from contact</h1>


<%= form_for(contact_path, method: "post") do %>
  <%= text_field_tag :subject, nil, placeholder: "objet" %>
  <%= text_field_tag :email_from, nil, placeholder: "adresse email" %>
  <%= text_field_tag :message_content, nil, placeholder: "petits mots doux." %>
        <button class="button">envoyer</button>


<% end %>

app/views/pages/home.html.erb
<div id="home-wrapper">

  <div id="product-images">
    <%= image_tag 'deuxmilledixneuf-cover_1.jpg', id: 'main-image' %>
    <%= image_tag 'deuxmilledixneuf-portrait-1.jpg', id: 'portrait-image' %>
  </div>

  <div id="product-details">

    <div id="content-details">
      <h1>deux mille dix neuf</h1>
      <h3>par cdlt, bisou.</h3>
      <h4>maxi calendrier</h4>

      <div class="product-description">
        <p>calendrier géant 2019<br>
          janvier à décembre, avec un petit coin pour glisser toutes les notes du mois + un aperçu du mois suivant.
        </p>
        <p>
          24’ x 32’ (environ 60 x 80 cm) <br>
          imprimé sur un papier blanc lisse <br>
          douze feuilles brochées, le tout perforé pour pouvoir être accroché au mur.
        </p>

        <p class="price">52.00 $</p>
      </div>

      <%= form_tag orders_path do %>
        <%= hidden_field_tag 'calendar_id', @calendar.id %>
        <%= text_field_tag :user_email, nil, placeholder: "adresse email" %>
        <button class="button">commander</button>
      <% end %>

      <div id="date-limite">
        <p>livraison dans le monde entier, yay. <br>
          option de livraison à choisir à l'étape suivante.
         </p>
      </div>

    </div> <!-- end of #content-details -->

  </div> <!-- end of #product-details -->

</div> <!-- end of #home-wrapper -->

app/views/pages/styles.html.erb
<div class="styles-sections">
  <p>font scheme</p>
</div>

<div class="container">

  <h1>this is a h1 header</h1>
  <p>Alohamora wand elf parchment, Wingardium Leviosa hippogriff, house dementors betrayal. Holly, Snape centaur portkey ghost Hermione spell bezoar Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks. Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall. </p>
  <p>Alohamora wand elf parchment, Wingardium Leviosa hippogriff, house dementors betrayal. Holly, Snape centaur portkey ghost Hermione spell bezoar Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks. Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall Diadem 10 galleons Thieves Downfall. Ministry-of-Magic mimubulus mimbletonia Pigwidgeon knut phoenix feather other minister Azkaban. Hedwig Daily Prophet treacle tart full-moon Ollivanders You-Know-Who cursed. Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks.</p>

  <h2>this is a h2 header</h2>
  <p>Holly, Snape centaur portkey ghost Hermione spell bezoar Scabbers. Peruvian-Night-Powder werewolf, Dobby pear-tickle half-moon-glasses, Knight-Bus. Padfoot snargaluff seeker: Hagrid broomstick mischief managed. Snitch Fluffy rock-cake, 9 ¾ dress robes <span class="accent-text">we could have been killed. or worst, expelled.</span>  Mudbloods yew pumpkin juice phials Ravenclaw’s Diadem 10 galleons Thieves Downfall. Ministry-of-Magic mimubulus mimbletonia Pigwidgeon knut phoenix feather other minister Azkaban. Hedwig Daily Prophet treacle tart full-moon Ollivanders You-Know-Who cursed. Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks.</p>

  <p>Red hair crookshanks bludger Marauder’s Map Prongs sunshine daisies butter mellow Ludo Bagman. Beaters gobbledegook N.E.W.T., Honeydukes eriseD inferi Wormtail. Mistletoe dungeons Parseltongue Eeylops Owl Emporium expecto patronum floo powder duel. Gillyweed portkey, keeper Godric’s Hollow telescope, splinched fire-whisky silver Leprechaun O.W.L. stroke the spine. Chalice Hungarian Horntail. Diadem 10 galleons Thieves Downfall. Ministry-of-Magic mimubulus mimbletonia Pigwidgeon knut phoenix feather other minister Azkaban. Hedwig Daily Prophet treacle tart full-moon Ollivanders You-Know-Who cursed. Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks.</p>

  <h3>this is a h3 header</h3>
  <p>Alohamora wand elf parchment, Wingardium Leviosa hippogriff, house dementors betrayal. Holly, Snape centaur portkey ghost Hermione spell bezoar Scabbers. Peruvian-Night-Powder werewolf, Dobby pear-tickle half-moon-glasses, Knight-Bus.

  Hedwig Daily Prophet treacle tart full-moon Ollivanders You-Know-Who cursed. Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks. Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall. </p>

  <p>Red hair crookshanks bludger Marauder’s Map Prongs sunshine daisies butter mellow Ludo Bagman. Beaters gobbledegook N.E.W.T., Honeydukes eriseD inferi Wormtail. Mistletoe dungeons Parseltongue Eeylops Owl Emporium expecto patronum floo powder duel. Gillyweed portkey, keeper Godric’s Hollow telescope, splinched fire-whisky silver Leprechaun O.W.L. stroke the spine. Chalice Hungarian Horntail. Diadem 10 galleons Thieves Downfall. Ministry-of-Magic mimubulus mimbletonia Pigwidgeon knut phoenix feather other minister Azkaban. Hedwig Daily Prophet treacle tart full-moon Ollivanders You-Know-Who cursed. Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks.</p>

  <h4>this is a h4 header</h4>
  <p>Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall. Nearly-Headless Nick now string them together, and answer me this, which creature would you be unwilling to kiss? Poltergeist sticking charm, troll umbrella stand flying cars golden locket Lily Potter. Pumpkin juice Trevor wave your wand out glass orbs, a Grim knitted hats. Stan Shunpike doe patronus, suck his soul Muggle-Born large order of drills the trace. Bred in captivity fell through the veil, quaffle blue flame ickle diddykins Aragog. Yer a wizard, Harry Doxycide the woes of Mrs. Weasley Goblet of Fire.</p>
  <p>here are all the horizontal bars</p>

  <hr class="lg-border-blue">
  <hr class="md-border-blue">
  <hr class="sm-border-blue">


  <h5>this is a h5 header</h5>
  <p>Red hair crookshanks bludger Marauder’s Map Prongs sunshine daisies butter mellow Ludo Bagman. Beaters gobbledegook N.E.W.T., Honeydukes eriseD inferi Wormtail. Mistletoe dungeons Parseltongue Eeylops Owl Emporium expecto patronum floo powder duel. Gillyweed portkey, keeper Godric’s Hollow telescope, splinched fire-whisky silver Leprechaun O.W.L. stroke the spine. Chalice Hungarian Horntail. Diadem 10 galleons Thieves Downfall. Ministry-of-Magic mimubulus mimbletonia Pigwidgeon knut phoenix feather other minister Azkaban. Hedwig Daily Prophet treacle tart full-moon Ollivanders You-Know-Who cursed. Fawkes maze raw-steak Voldemort Goblin Wars snitch Forbidden forest grindylows wool socks.</p>

  <h6>this is a h6 header</h6>

  <p>Red hair crookshanks bludger Marauder’s Map Prongs sunshine daisies butter mellow Ludo Bagman. Beaters gobbledegook N.E.W.T., Honeydukes eriseD inferi Wormtail. Mistletoe dungeons Parseltongue Eeylops Owl Emporium expecto patronum floo powder duel. Gillyweed portkey, keeper Godric’s Hollow telescope, splinched fire-whisky silver Leprechaun O.W.L. stroke the spine. Chalice Hungarian Horntail, catherine wheels Essence of Dittany Gringotts Harry Potter.
  Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall. Nearly-Headless Nick now string them together, and answer me this, which creature would you be unwilling to kiss? Poltergeist sticking charm, troll umbrella stand flying cars golden locket Lily Potter. Pumpkin juice Trevor wave your wand out glass orbs, a Grim knitted hats. Stan Shunpike doe patronus, suck his soul Muggle-Born large order of drills the trace. Bred in captivity fell through the veil, quaffle blue flame ickle diddykins Aragog. Yer a wizard, Harry Doxycide the woes of Mrs. Weasley Goblet of Fire.</p>
</div>

<div class="styles-sections">
  <p>color scheme</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-2">
      <p>dark gray / <br>#3F3F40</p>
      <p class="styles-colors dark-gray"></p>
    </div>
    <div class="col-xs-2">
      <p>medium gray / <br>#9A9A9A</p>
      <p class="styles-colors medium-gray"></p>
    </div>
    <div class="col-xs-2">
      <p>light gray / <br>#F4F4F4</p>
      <p class="styles-colors light-gray"></p>
    </div>
    <div class="col-xs-2">
      <p>dark-blue / <br>#10131C</p>
      <p class="styles-colors dark-blue"></p>
    </div>
    <div class="col-xs-2">
      <p>neon orange / <br>#F15156</p>
      <p class="styles-colors neon"></p>
    </div>
    <div class="col-xs-2">
      <p>peach orange / <br>#FFCB96</p>
      <p class="styles-colors peach"></p>
    </div>
  </div>
</div>

<div class="styles-sections">
  <p>components scheme</p>
</div>

<div class="container">
  <div class="row">
    <div id="buttons-styles">
      <div><%= link_to "i'm a button", '#', class: "button" %> </div>
      <div><%= link_to "i'm a button", '#', class: "button accent-button" %> </div>
    </div>

  </div>
</div>

app/views/partials/shared/_footer.html.erb
<% if action_name == "home" %>

  <div id="home-footer">


    <div id="mail-link">
      <a data-sharer="email" data-title="maxi calendrier" data-url="<%= root_url %>" data-subject="hey! si jamais tu cherches une idée de cadeau de noël, voici quelque chose qui me plaira beaucoup beaucoup beaucoup." data-to="some@email.com">transmettre subtilement cette idée cadeau</a>
    </div>

    <div id="main-share-links">
      <a data-sharer="twitter" data-url="<%= root_url %>">partager sur twitter</a>
      <a data-sharer="facebook" data-url="<%= root_url %>">partager sur facebook</a>
    </div>

    <div id="footer-content">
      <%= image_tag 'deuxmilledixneuf-cover_2.jpg', id: 'paysage-image' %>
      <p>cdlt, bisou. tous droits réservés.</p>
    </div>


    <div id="mentions-legales">
      <%= link_to 'contact', 'mailto:salut@cdltbisou.com', class: 'accent-text' %>
    </div>

  </div>

<% else %>

  <div id="main-footer" class="content">
    <div id="footer-credits">
        <p>
          cdlt, bisou. <br>
          tous droits réservés.
        </p>

      <div id="footer-important-stuff">
      <%= link_to 'contact', 'mailto:salut@cdltbisou.com', class: 'accent-text' %>
      </div>
    </div>
  </div>


<% end %>

app/views/partials/shared/_navbar.html.erb
<% unless action_name == "home" || action_name == "thanks"%>

  <div id="pages-navbar" class="navbar-container">
    <div id="home-link">
      <%= link_to root_path do %>
        <h1 class="button-inverted">deux mille dix neuf</h1>
      <% end %>
      <h2>par cdlt,bisou.</h2>
    </div>
  </div>

<% end %>

app/views/payments/new.html.erb
<h1>Purchase of <%= @order.product_name %></h1>

<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>total amount : <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="calendar"
    data-email="<%= @order.user_email %>"
    data-description="Teddy <%= @order.product_name%>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>

<% end %>